name: Auto Link Fixer

on:
  schedule:
    # This tells GitHub to run every 5 minutes
    - cron: '*/5 * * * *'
  # This keeps the manual "Run workflow" button active
  workflow_dispatch:
  # This makes the bot run every time you save code
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RHASH: ${{ secrets.RHASH }}
        run: python link_fixer.py
        
